/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmMessage.java
 *
 * Created on Oct 31, 2012, 4:57:33 PM
 */

package multisecure;
import java.sql.*;
import java.io.*;
import java.math.*;
/**
 *
 * @author access
 */
public class frmMessage extends javax.swing.JFrame {
ConnectDatabase cd=new ConnectDatabase();
    /** Creates new form frmMessage */
    public frmMessage() {
        initComponents();
        txtEncrypt.setText("");
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSubject = new javax.swing.JTextField();
        cmbGroup = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCompose = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblP = new javax.swing.JLabel();
        lblQ = new javax.swing.JLabel();
        txtEncrypt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleBackground"));

        jLabel1.setText("Subject");

        jLabel2.setText("Sender Name");

        jLabel3.setText("Sender Group Name");

        jLabel4.setText("Compose Message");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sendto.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sendtoall.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });

        cmbGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Group 1", "Group 2", "All" }));
        cmbGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGroupItemStateChanged(evt);
            }
        });
        cmbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGroupActionPerformed(evt);
            }
        });

        txtCompose.setColumns(20);
        txtCompose.setRows(5);
        jScrollPane1.setViewportView(txtCompose);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signature.jpg"))); // NOI18N

        jLabel6.setText("Public Key");

        jButton4.setText("Get key");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblP.setText("-");

        lblQ.setText("-");

        txtEncrypt.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(78, 78, 78)
                                .addComponent(txtSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(lblP, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choice1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbGroup, 0, 149, Short.MAX_VALUE)
                                        .addGap(20, 20, 20)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56)
                        .addComponent(lblQ)
                        .addGap(41, 41, 41)
                        .addComponent(jButton4))
                    .addComponent(txtEncrypt))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton4)
                    .addComponent(lblQ)
                    .addComponent(lblP))
                .addGap(60, 60, 60)
                .addComponent(txtEncrypt)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, 0, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        long start,end;
        start=System.currentTimeMillis();
                RSA rsa=new RSA(8);
       // String plaintext="hello";
         //       System.out.println( "" ) ;
//txtInput.setText(plaintext);
		// Encrypt Message
		BigInteger[] ciphertext = rsa.encrypt(txtCompose.getText()) ;

		//System.out.print( "Ciphertext: [" ) ;
		for( int i = 0 ; i < ciphertext.length ; i++ )
		{

//String str=ciphertext[i].toString( 16 ).toUpperCase();
			//System.out.print( ciphertext[i].toString( 16 ).toUpperCase() ) ;

			//if( i != ciphertext.length - 1 )
			//	System.out.print( " " ) ;
                      txtEncrypt.setText(ciphertext[i].toString( 16 ).toUpperCase());
		}

                
//                System.out.println(str);
		//System.out.println( "]" ) ;
		//System.out.println( "" ) ;

		//RSA rsa1 = new RSA(8);

		//String recoveredPlaintext = rsa1.decrypt( ciphertext ,rsa.getD(),rsa.getN()) ;

		//System.out.println( "Recovered plaintext: [" + recoveredPlaintext + "]" ) ;


//String p=null;
//String q=null;

        try
        {
           FileInputStream f=new FileInputStream("file.txt");
           DataInputStream in=new DataInputStream(f);
           BufferedReader br=new BufferedReader(new InputStreamReader(in));
           String str;
           if((str=br.readLine())!=null)
           {
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/multisecure","root","");
            //Statement st=con.createStatement();
            cd.st1.execute("insert into message(subject,grp,userid,message,fromUser,encrypt_msg) values('"+txtSubject.getText()+"','"+cmbGroup.getSelectedItem()+"','"+choice1.getSelectedItem()+"','"+txtCompose.getText()+"','"+str+"','"+txtEncrypt.getText()+"')");
            txtEncrypt.setText("");
           }

            
           
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }

                end=System.currentTimeMillis()-start;

String str=String.valueOf(end/1000d);
try
{
    Writer out=null;
    File f=new File("file_rsa.txt");
    out=new BufferedWriter(new FileWriter(f));
    out.write(str);
    out.close();
}
catch(Exception ex){}



    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String grp="";
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/multisecure","root","root");
            for(int i=0;i<=choice1.getItemCount();i++)
            {
              //Statement st=con.createStatement();
              ResultSet rs=cd.st1.executeQuery("select * from register where uname='"+choice1.getItem(i).toString()+"'");
              if(rs.next())
              {
                grp=rs.getString("grp");
              }
               cd.st1.execute("insert into message(subject,grp,userid,message) values('"+txtSubject.getText()+"','"+grp+"','"+choice1.getItem(i).toString()+"','"+txtCompose.getText()+"')");
            

            }
            
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtCompose.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGroupActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbGroupActionPerformed

    private void cmbGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGroupItemStateChanged
        // TODO add your handling code here:
       
        choice1.removeAll();
        try
        {
            boolean All=false;
            if(cmbGroup.getSelectedItem().equals("All"))
            {

            All=true;
            }
            if(All)
            {
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/multisecure","root","");
            //Statement st=con.createStatement();
            ResultSet rs=cd.st1.executeQuery("select uname from register");
            while(rs.next())
            {
             choice1.add(rs.getString("uname"));
            }
            }
            if(!All)
            {
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/multisecure","root","");
            //Statement st=con.createStatement();
            ResultSet rs=cd.st1.executeQuery("select uname from register where grp='"+cmbGroup.getSelectedItem()+"'");
            while(rs.next())
            {
               // cmbSender.add(rs.getString("uname"));
                choice1.add(rs.getString("uname"));
            }
            }

        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cmbGroupItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
try
{
        //Class.forName("com.mysql.jdbc.Driver");
        //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/multisecure","root","");
        //Statement st=con.createStatement();
        ResultSet rs=cd.st1.executeQuery("select * from register where uname='"+choice1.getSelectedItem()+"'");
        while(rs.next())
        {
            lblP.setText(rs.getString("pubkey_p"));
            lblQ.setText(rs.getString("pubkey_q"));
        }
}
catch(Exception ex)
{
    System.out.println(ex.getMessage());
}

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JComboBox cmbGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblQ;
    private javax.swing.JTextArea txtCompose;
    private javax.swing.JLabel txtEncrypt;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables

}
