/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmShowGraph.java
 *
 * Created on Nov 30, 2012, 7:37:56 PM
 */

package multisecure;
import org.jfree.chart.*;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import org.jfree.chart.axis.*;
import org.jfree.chart.entity.*;
import org.jfree.chart.labels.*;
import org.jfree.chart.plot.*;
import org.jfree.chart.renderer.category.*;
import org.jfree.chart.urls.*;
import org.jfree.data.category.*;
import org.jfree.data.general.*;


/**
 *
 * @author access
 */
public class frmShowGraph extends javax.swing.JFrame {
String str1,str2;
    /** Creates new form frmShowGraph */
    public frmShowGraph() {
        initComponents();
        try
        {
            FileInputStream f1=new FileInputStream("file_rsa.txt");
            FileInputStream f2=new FileInputStream("file_elgamal.txt");
            DataInputStream in1=new DataInputStream(f1);
            DataInputStream in2=new DataInputStream(f2);
            BufferedReader br1=new BufferedReader(new InputStreamReader(in1));
            BufferedReader br2=new BufferedReader(new InputStreamReader(in2));
            if((str1=br1.readLine())!=null)
            {

            }
            if((str2=br2.readLine())!=null)
            {

            }
            in1.close();
            in2.close();
        }
        catch(Exception ex)
        {

        }


                    final double[][] data = new double[][]{
                {Double.valueOf(str1)},
                {Double.valueOf(str2)}
            };

            final CategoryDataset dataset = DatasetUtilities.createCategoryDataset(
                    "", "", data);

            JFreeChart chart = null;
            BarRenderer renderer = null;
            CategoryPlot plot = null;


            final CategoryAxis categoryAxis = new CategoryAxis("");
            final ValueAxis valueAxis = new NumberAxis("Run");
            renderer = new BarRenderer();

            plot = new CategoryPlot(dataset, categoryAxis, valueAxis, renderer);
            plot.setOrientation(PlotOrientation.VERTICAL);
            chart = new JFreeChart("Performance Analysis of RSA Vs. Elgamal", JFreeChart.DEFAULT_TITLE_FONT, plot, true);

            chart.setBackgroundPaint(new Color(249, 231, 236));

            Paint p1 = new GradientPaint(
                    0.0f, 0.0f, new Color(16, 89, 172), 0.0f, 0.0f, new Color(201, 201, 244));
            renderer.setSeriesPaint(1, p1);

            Paint p2 = new GradientPaint(
                    0.0f, 0.0f, new Color(255, 35, 35), 0.0f, 0.0f, new Color(255, 180, 180));
            renderer.setSeriesPaint(2, p2);

            plot.setRenderer(renderer);

            try {
                final ChartRenderingInfo info = new ChartRenderingInfo(new StandardEntityCollection());
                final File file1 = new File("barchart.png");
                ChartUtilities.saveChartAsPNG(file1, chart, 600, 400, info);
                lblChart.setIcon(new ImageIcon("barchart.png"));
            } catch (Exception e) {
//                out.println(e);
            }
            


            


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChart = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChart.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblChart, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblChart, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmShowGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblChart;
    // End of variables declaration//GEN-END:variables

}
